### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by bayleedev** [mdx-dev/li3_charizard#2]
- [x] 1) Rename `QueryPartToString` to `QueryStringBuilder`
- [x] 2) groupby
- [x] 3) suggestions (funky `geo_zip_combo` schema thing)
- [x] 4) related
- [x] 5) analyze tests and remove unnecessary sections
- [x] 6) Add test for Provider Name Search
- [x] 7) Add test for Similar Providers
- [x] 8) Add test for Provider AC Search
- [x] 9) Add test for Provider Specialty Search
- [x] 10) Add test for Provider Disorder Search
- [ ] 11) Faceting method(s)
- [ ] 12) curl Query
- [ ] 13) Return/Parse results
- [ ] **A**) GroupBy
- [ ] **B**) Facets
- [x] 14) Geo sort
- [x] 15) Field List
- [ ] 16) Query Validator
- [ ] 17) Port _augmentResults logic into response processing, or wherever it belongs
